.\" vi:set wm=5
.Dd $Mdocdate: March 25 2013 $
.Dt SCREEN 1
.Sh screen
.Nm screen
.Nd Key Bindings
.Pp
.Bl -tag -width "XXXXXXXXXX" -offset indent -compact
.It C-a 
(select)
.It C-a \&"
(windowlist -b)
.It C-a 0-9
(select 0-9)
.It C-a -
(select -)
.It C-a tab
(focus)
.It C-a C-a
(other)
.It C-a a
(meta)
.It C-a A
(title)
.It C-a C-b
(break)
.It C-a B
(pow_break)
.It C-a C-c
(screen)
.It C-a C
(clear)
.It C-a C-d
(detach)
.It C-a D D
(pow_detach)
.It C-a C-f
(flow)
.It C-a F
(fit)
.It C-a C-g
(vbell)
.It C-a h
(hardcopy)
.It C-a H
(log)
.It C-a C-i
(info)
.It C-a C-k
(kill)
.It C-a C-l
(redisplay)
.It C-a L
(login)
.It C-a C-m
(lastmsg)
.It C-a M
(monitor)
.It C-a C-n
(next)
.It C-a N
(number)
.It C-a C-p
(prev)
.It C-a C-q
(xon)
.It C-a Q
(only)
.It C-a C-r
(wrap)
.It C-a C-s
(xoff)
.It C-a S
(split)
.It C-a C-t
(time)
.It C-a v
(version)
.It C-a C-v
(digraph)
.It C-a C-w
(windows)
.It C-a W
(width)
.It C-a C-x
(lockscreen)
.It C-a X
(remove)
.It C-a C-z
(suspend)
.It C-a Z
(reset)
.It C-a .
(dumptermcap)
.It C-a ?
(help)
.It C-a \e
(quit)
.It C-a :
(colon)
.It C-a esc
(copy)
.It C-a ]
(paste .)
.It C-a }
(history)
.It C-a >
(writebuf)
.It C-a <
(readbuf)
.It C-a =
(removebuf)
.It C-a ,
(license)
.It C-a _
(silence)
.It C-a |
(split -v)
.It C-a *
(displays)
.El
